# --------- PRIMARY DB ----------
spring.datasource.jdbc-url=jdbc:mysql://superme-database.c5cm4ayqqeiw.ap-south-1.rds.amazonaws.com:3306/mindfullP1?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password= 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------- ADMIN DB ----------
spring.admin.datasource.jdbc-url=jdbc:mysql://superme-database.c5cm4ayqqeiw.ap-south-1.rds.amazonaws.com:3306/mindfullAdmin?createDatabaseIfNotExist=true
spring.admin.datasource.username=admin
spring.admin.datasource.password=EOT2ENtMUASqeRJx7NvZ
spring.admin.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------- AWS ----------
cloud.aws.region=ap-south-1
cloud.aws.credentials.access-key=qwdeeddfdfwe2
cloud.aws.credentials.secret-key= deffrferdf
s3.bucket=mfd-public
