# --------- PRIMARY DB ----------
spring.datasource.jdbc-url=jdbc:mysql://187.127.142.16:3306/mindfullP1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------- ADMIN DB ----------
spring.admin.datasource.jdbc-url=jdbc:mysql://187.127.142.16:3306/mindfullAdmin?createDatabaseIfNotExist=true
spring.admin.datasource.username=root
spring.admin.datasource.password=Root@1234
spring.admin.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------- AWS (Dummy for local) ----------
cloud.aws.region=ap-south-1
cloud.aws.credentials.access-key=h655h4u67
cloud.aws.credentials.secret-key=v4v54yb567
s3.bucket=mfd-public
