# --------- PRIMARY DB ----------
spring.datasource.jdbc-url=jdbc:mysql://187.127.142.16:3306/mindfullP1?createDatabaseIfNotExist=true
#spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/mindfullP1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@1234
#spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------- ADMIN DB ----------
spring.admin.datasource.jdbc-url=jdbc:mysql://187.127.142.16:3306/mindfullAdmin?createDatabaseIfNotExist=true
#spring.admin.datasource.jdbc-url=jdbc:mysql://localhost:3306/mindfullAdmin?createDatabaseIfNotExist=true
spring.admin.datasource.username=root
spring.admin.datasource.password=Root@1234
#spring.admin.datasource.password=root
spring.admin.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------- AWS (Dummy for local) ----------
cloud.aws.region=ap-south-1
cloud.aws.credentials.access-key=h655h4u67
cloud.aws.credentials.secret-key=v4v54yb567
s3.bucket=mfd-public



# ==========================================
# OAuth2 Social Login Configuration (ADD THIS)
# ==========================================

# ==========================================
# OAuth2 Social Login (NEW - Does NOT affect existing)
# ==========================================

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=252432866529-v1gcoajd53i39qkoln08pg7tkr1ugpf6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=https://api.supermeapp.com/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=get.supermeapp@gmail.com
spring.mail.password=ovuz slib tsip kdyk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


