package com.superme.enums;

public enum ActivityType {
    HABIT_COMPLETED,
    TASK_COMPLETED,
    QUIZ_COMPLETED,
    PUZZLE_COMPLETED,
    ARTICLE_COMPLETED,
    CHALLENGE_COMPLETED,
    REEL_CREATED,
    PET_ENHANCED,
    REEL_LIKED, LESSON_COMPLETED, APP_OPENED
}

